/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://cjmmtz7ylrgm7c2wkgbbb7a2wq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-2:ebacc17f-4a07-4eea-a6b0-c35666616db9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_j2DbZN3nM",
    "aws_user_pools_web_client_id": "4r0oktghv426fo138g1vr1dsg4",
    "oauth": {}
};


export default awsmobile;
